packages:
  - "apps/web"
  - "packages/design-system"
  - "packages/env"
  - "packages/next-config"
  - "packages/seo"
  - "packages/storage"
  - "packages/tailwind-config"
  - "packages/typescript-config"
